### ISSUE TITLE
Change axis title when changing data plotted

### ISSUE THREAD

**Issue by mtat76** [mtat76/exscalabar#7]
Need to figure out how to change the y-label axis name on the plot when a new plot is selected.  I have supplied a dropdown on crd.html as well as a file crd.js to put the code in...

**Comment by danbek** [comment]
Don't quite understand this. Right now the plot has 5 traces, and you can select/deselect which traces are displayed by clicking on the names or circles in the legend. Changing which traces are plotting shouldn't change the label on the y-axis, right?

Do you mean that selecting different values in the drop-down should change the plot to an entirely different set of traces? E.g., one set of plots might be plotting extinction in units of inverse length, while another set would be temperatures, or pressures?

So you need to be accumulating multiple sets of data in the background, and you can choose which set via the drop-down?

**Comment by mtat76** [comment]
You got it....

I should sit down with you and discuss the layout of these pages to see if you have any better ideas...

**Comment by danbek** [comment]
Some time Tuesday?

On Sun, Apr 19, 2015 at 9:22 PM, Matt Richardson <notifications@github.com>
wrote:

> You got it....
>
> I should sit down with you and discuss the layout of these pages to see if
> you have any better ideas...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/issues/7#issuecomment-94346428>.
>



-- 
Dan Becker

**Comment by mtat76** [comment]
Should be fine....when?

**Comment by danbek** [comment]
My day is pretty open, say 3:00 PM?

On Mon, Apr 20, 2015 at 10:24 PM, Matt Richardson <notifications@github.com>
wrote:

> Should be fine....when?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/issues/7#issuecomment-94633949>.
>



-- 
Dan Becker

**Comment by mtat76** [comment]
Should work.  Where?

**Comment by danbek** [comment]
This afternoon is looking bad now, I could stop by your place after 8:15
tonight, or we could wait for tomorrow.

Dan

On Tue, Apr 21, 2015 at 11:37 AM, Matt Richardson <notifications@github.com>
wrote:

> Should work. Where?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/issues/7#issuecomment-94881871>.
>



-- 
Dan Becker

**Comment by mtat76** [comment]
Tomorrow is fine.

**Comment by danbek** [comment]
Should we meet in Longmont right after drop-off at TPCA?

On Tue, Apr 21, 2015 at 1:50 PM, Matt Richardson <notifications@github.com>
wrote:

> Tomorrow is fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/issues/7#issuecomment-94917898>.
>



-- 
Dan Becker
